module.exports = {
    GAME_SERVER_CONNECT: 1,
    GAME_SERVER_DISCONNECT: 3,
    GAME_SERVER_HEARTBEAT: 4,
    GAME_SERVER_GAME_STATUS: 150,
    GAME_SERVER_USER_IN: 151,
    GAME_SERVER_USER_OUT: 152,
    GAME_SERVER_SYNC_USERS: 155,
    GAME_SERVER_USER_MANOR_SOLD: 156,
    GAME_SERVER_REPORT_FRAME_TIME: 161,
    GAME_SERVER_HTTP_SECRET: 164,
    GAME_SERVER_CONNECTOR_MESSAGE: 10001,

    ROOM_MANAGER_CONNECT_REPLY: 2,
    ROOM_MANAGER_USER_ATTRIBUTE: 154,
    ROOM_MANAGER_USER_MANOR_RELEASE: 157,
    ROOM_MANAGER_BROADCAST_MESSAGE: 158,
    ROOM_MANAGER_SELECTABLE_ACTION_INFO: 159,
    ROOM_MANAGER_KICK_USER_OUT: 160,
    ROOM_MANAGER_HTTP_SECRET: 163,
    ROOM_MANAGER_CONNECTOR_MESSAGE: 10002
}